services:
  bumpgen:
    image: ollyscoding/bumpgen
    container_name: bumpgen
    restart: "unless-stopped"
    volumes:
      - /opt/bumpgen:/config
      - /path/to/your/output:/output
      - /path/to/your/background-content:/background-content
