name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      # We don't want to do all the node-gyp stuff
      - run: npm install --ignore-scripts
      - run: npm run tsc
      - run: npm run lint
      - run: npm run prettier
