name: dev

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Gets the package.json
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ollyscoding/bumpgen-test:${{ steps.package-version.outputs.current-version }}-${{ env.COMMIT_SHORT_SHA }}
      - uses: actions/github-script@v7
        with:
          script: |
            if (context.issue.number) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Published dev build ollyscoding/bumpgen-test:${{ steps.package-version.outputs.current-version }}-${{ env.COMMIT_SHORT_SHA }}'
              })
            }
